### ISSUE TITLE
Refactor Logging Appearance

### ISSUE THREAD

**Issue by reinhello** [reinhello/givies-framework#5]
Would anyone want an improvement with the `Logger` class message appearance? 

Here's the comparison between the old logging and the new one:

### OLD

![image](https://user-images.githubusercontent.com/73813638/162601943-d1eb2524-2dd3-463b-a1c5-cab8d335f8bb.png)

### NEW

![image](https://user-images.githubusercontent.com/73813638/162602066-e35263ac-0c82-4a08-adfc-467c04c510a9.png)

**Comment by DragonDev15** [comment]
I like the start of the New Logger:

<img width="235" alt="image" src="https://user-images.githubusercontent.com/70057141/162617297-12c5d8fb-8d8d-4f60-aaf4-517017b5c6de.png">

With the ending of the old one
<img width="539" alt="image" src="https://user-images.githubusercontent.com/70057141/162617318-f7e9d7f0-33b2-43b1-a1f0-4c40884700b4.png">

Personal preference, everyone is different.

**Comment by reinhello** [comment]
Yeah, sounds good. We can do that.

**Comment by reinhello** [comment]
Does this look better now?

![image](https://user-images.githubusercontent.com/73813638/162618510-1abc72eb-086c-4217-b60e-0c66ac8a85fb.png)

**Comment by DragonDev15** [comment]
Yes it does.
